### ISSUE TITLE
Add config and solid-nextcloud app to nextcloud-server

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/test-suites#17]
I added the rudimentary https://github.com/pdsinterop/test-suites/blob/master/servers/nextcloud-server/Dockerfile which runs Nextcloud on port 443, but it shows the initial "configure me" screen. We should probably add in a `config.php` file which creates a user `alice' / '123', adds in our Nextcloud app, and enables it.

**Comment by michielbdejong** [comment]
CC @poef

**Comment by michielbdejong** [comment]
As discussed in yesterday's meeting, I'll have a go at this.
```sh
docker build -t nextcloud-server ./servers/nextcloud-server
docker run -p 443:443 nextcloud-server
```
gets you quite far, but it still says 'installatie afronden' when you then go to https://localhost (take into account https://stackoverflow.com/a/31900210):
![Screenshot 2020-07-07 10 31 54](https://user-images.githubusercontent.com/408412/86748982-2c7aba00-c03d-11ea-89df-ebbeba5230e8.png)

**Comment by michielbdejong** [comment]
Here's an example xhr from that page, enabling an app:
```js
fetch("https://localhost/settings/apps/enable", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr-FR;q=0.6,fr;q=0.5,de-DE;q=0.4,de;q=0.3,es-ES;q=0.2,es;q=0.1,id-ID;q=0.1,id;q=0.1",
    "content-type": "application/json;charset=UTF-8",
    "requesttoken": "4epXerWt63khuXxtdp62FqcziLBTPMGgwaYFz+KlONw=:uaw4A8+euzRk+E8GGKadXddA3OMyRbfB6slv+LbnS7c=",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "cookie": "__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oc_sessionPassphrase=47LAL7XMtNhB8LhRCBEmgbieshuMZfFsFa0XRzmnFtOIb2YJyRr67a%2FoVHw86ad6Lp%2BBrwB8XrMKoEkZz1rdvKvAmLvKGILj7ttM7QIfNWhgDpzJxvuX9%2BVIjDL6EpHa; oc37ayxue1jc=b924c8f870bf2cf5e97096ceeb49b0b9"
  },
  "referrerPolicy": "no-referrer",
  "body": "{\"appIds\":[\"richdocumentscode\"],\"groups\":[]}",
  "method": "POST",
  "mode": "cors"
});

**Comment by michielbdejong** [comment]
![Screenshot 2020-07-07 11 12 08](https://user-images.githubusercontent.com/408412/86756487-b5e0bb00-c042-11ea-8281-c3d3fa827f4b.png)

**Comment by michielbdejong** [comment]
I got it working but it requires user interaction:
* create an admin user `alice` / `123`.
* log in and click through the welcome wizard
* search for the 'PDS-Interop' app
* click 'enable unapproved app'
* click 'enable app'

![Screenshot 2020-07-07 11 44 39](https://user-images.githubusercontent.com/408412/86762963-4b7e4980-c047-11ea-8134-d2a447a4db62.png)

**Comment by michielbdejong** [comment]
I got it working with a separate init script now.

**Comment by michielbdejong** [comment]
![Screenshot 2020-07-07 13 01 09](https://user-images.githubusercontent.com/408412/86771093-f1cf4c80-c051-11ea-8987-d48d06594fa4.png)

**Comment by poef** [comment]
Awesome!
